# Gradle settings
org.gradle.configuration-cache=false
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
teaVmVersion=0.13.0-nge
androidCompileSdk=36
androidMinSdk=33
androidTargetSdk=33

# NGE versions
ngePlatformVersion=0.2.0-SNAPSHOT
ngeVersion=0.2.0-SNAPSHOT
libjgliosVersion=0.3-SNAPSHOT
