plugins {
    id 'com.android.application'
}

def androidCompileSdkVersion = (findProperty('androidCompileSdk') ?: 36).toString().toInteger()
def androidMinSdkVersion = (findProperty('androidMinSdk') ?: 33).toString().toInteger()
def androidTargetSdkVersion = (findProperty('androidTargetSdk') ?: 33).toString().toInteger()

android {
    compileSdk androidCompileSdkVersion
    namespace "${project.Namespace}"  

    defaultConfig {
        applicationId "${project.Namespace}"
        minSdk androidMinSdkVersion
        targetSdk androidTargetSdkVersion
        versionCode  project.VersionCode.toInteger()
        versionName  project.Version
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        manifestPlaceholders = [
            appLabel         : (project.findProperty('Title') ?: "NGE Unnamed App"),
            screenOrientation: (project.findProperty('ScreenOrientation') ?: "landscape")
        ]
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
    }


}


dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    testImplementation libs.junit.v4133snapshot
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core


    implementation project(':app') 
    implementation "org.ngengine:nge-platform-android:${ngePlatformVersion}"
    implementation "org.ngengine:nge-app:${ngeVersion}"
    implementation "org.ngengine:nge-android:${ngeVersion}"

}

apply from: "${rootDir}/gradle/libs/android-icon-gen.gradle"

task generateAndroidLauncherIcons (){
    doLast {
        gradle.ext.generateAndroidIcons("${rootDir}/icon.png", "${projectDir}/src/main/res")
    }
}

android.applicationVariants.all { variant ->
    variant.mergeResourcesProvider.configure { dependsOn(generateAndroidLauncherIcons) }
}
